/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        background: '#faf8ff',
        'surface-container': '#ededf8',
        'secondary-fixed-dim': '#71dba6',
        'on-tertiary-fixed-variant': '#812800',
        'surface-container-lowest': '#ffffff',
        primary: '#003d9b',
        secondary: '#006c47',
        'surface-tint': '#0c56d0',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#005235',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#ffdbcf',
        'on-tertiary-fixed': '#380d00',
        'primary-fixed': '#dae2ff',
        'surface-container-high': '#e7e7f2',
        'tertiary-fixed-dim': '#ffb59b',
        'surface-bright': '#faf8ff',
        'on-secondary-container': '#00714b',
        'secondary-fixed': '#8df7c1',
        outline: '#737685',
        'on-primary-container': '#c4d2ff',
        'error-container': '#ffdad6',
        'on-surface': '#191b23',
        'outline-variant': '#c3c6d6',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'secondary-container': '#8af5be',
        'surface-dim': '#d9d9e4',
        'on-primary-fixed-variant': '#0040a2',
        'on-surface-variant': '#434654',
        'on-primary-fixed': '#001848',
        'inverse-primary': '#b2c5ff',
        'primary-container': '#0052cc',
        tertiary: '#7b2600',
        'primary-fixed-dim': '#b2c5ff',
        'on-tertiary-container': '#ffc6b2',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'tertiary-container': '#a33500',
        'on-secondary-fixed': '#002113',
        'on-background': '#191b23',
        'inverse-surface': '#2e3038',
        'surface-container-low': '#f3f3fd',
        'surface-variant': '#e1e2ec',
        'inverse-on-surface': '#f0f0fb',
        'surface-container-highest': '#e1e2ec',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
};

